sudo: false
language: node_js
node_js:
  - 8

before_install:
# Get installer script.
  - wget https://raw.githubusercontent.com/nodeGame/nodegame/master/bin/nodegame-installer.js
  - chmod a+x nodegame-installer.js

install:
  - npm install --only=dev
  - node nodegame-installer.js @dev --install-dir node_modules --no-spinner --branch v4 --yes
  - mv node_modules/JSUS/node_modules/resolve node_modules/
  - mv node_modules/fs-extra/node_modules/resolve node_modules/
  

script:
# Add JSUS tests here.
  - ls -la node_modules/JSUS/node_modules/
  - ls -la node_modules/
  - npm test

# Test Ultimatum game.
  - cd node_modules/nodegame-test/games/ultimatum-game
  - ./bin/run-standalone-test-v4.sh
