sudo: false
language: node_js
node_js:
  - 0.12
  - 4.5
  - 6.9

before_install:
# Get installer script.
  - cd bin
  - wget https://github.com/nodeGame/nodegame/raw/master/bin/install-nodegame-for-module.sh
  - chmod a+x install-nodegame-for-module.sh
  - cd ..

install:
# Share node_modules with nodeGame.
  - mkdir -p nodegame node_modules
  - ln -s ../node_modules nodegame/node_modules
  - ln -s .. node_modules/JSUS
# If "install-nodegame-for-module.sh" is called before "npm install",
# it gives an error.
  - npm install
  - bin/install-nodegame-for-module.sh -g "nodegame-window nodegame-widgets NDDB shelf.js nodegame-client nodegame-server descil-mturk nodegame-requirements nodegame-monitor nodegame-db nodegame-mongodb"


script:
# Test JSUS.
  - npm test
# Test Ultimatum game.
  - cd nodegame/games
  - git clone https://github.com/nodeGame/ultimatum.git
  - cd ultimatum
  - ./bin/run-standalone-test.sh
