sudo: false
language: node_js
node_js:
  - 10
  - 12

before_install:
# Get installer script.
  - wget https://raw.githubusercontent.com/nodeGame/nodegame/master/bin/nodegame-installer.js
  - chmod a+x nodegame-installer.js

install:
  - npm install --only=dev
  # --branch v4
  - node nodegame-installer.js @dev --install-dir node_modules --no-spinner --yes --no-check-parent-dir
  # - mv node_modules/JSUS/node_modules/resolve node_modules/
  # - mv node_modules/JSUS/node_modules/fs-extra node_modules/
  

script:
# Add JSUS tests here.
  # - ls -la node_modules/JSUS/node_modules/
  # - ls -la node_modules/
  - npm test

# Test Ultimatum game.
  - cd node_modules/nodegame/games/ultimatum-game
  - ./bin/run-standalone-test-v4.sh
